spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cybersecurity_app_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace


application:
  security:
    jwt:
      secret-key: a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f61234