-- CREA TABLA CONTENIDOS

/*
CREATE TABLE Contenidos (
    id_contenido INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    cuerpo TEXT NOT NULL,
    tema VARCHAR(100),
    nivel_dificultad VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

*/

-- AGREGAR CONTENIDO A LAS TABLAS
/*
INSERT INTO Contenidos (titulo, cuerpo, tema, nivel_dificultad) VALUES
(
    '¿Qué es el Phishing y Cómo Reconocerlo?',
    'El phishing es una de las tácticas de ciberdelincuencia más persistentes y engañosas, clasificada dentro de la ingeniería social. Su objetivo primordial es suplantar la identidad de una persona, empresa o servicio de confianza (bancos, plataformas de correo, redes sociales, organismos gubernamentales, o incluso directivos de la propia empresa en ataques de ''whaling'') para inducir a la víctima a revelar información personal y confidencial. Esta información puede incluir credenciales de acceso (nombres de usuario y contraseñas), detalles de tarjetas de crédito, números de identificación personal, o información bancaria. Los canales más comunes para perpetrar ataques de phishing son el correo electrónico, pero también se utilizan mensajes de texto (SMiShing), mensajes instantáneos en redes sociales, y llamadas telefónicas (Vishing), donde el atacante puede incluso usar software para falsear el número de origen.\n    Existen variantes más dirigidas y, por tanto, más peligrosas, como el ''spear phishing'', que se personaliza para un individuo o grupo específico utilizando información previamente recolectada sobre ellos, haciendo el engaño mucho más convincente. Reconocer un intento de phishing requiere un ojo crítico y atención al detalle. Algunas señales de alerta incluyen: una dirección de correo electrónico del remitente que, aunque parecida, no coincide exactamente con la oficial (ej: ''banco@soporte-seguro.com'' en lugar de ''soporte@banco.com''); errores gramaticales, ortográficos o de formato en el mensaje; un tono de urgencia o amenaza desmedido (ej: ''su cuenta será bloqueada si no actúa inmediatamente''); solicitudes inesperadas de información personal o financiera; y enlaces que al posar el cursor sobre ellos (sin hacer clic) revelan una URL de destino diferente a la que aparentan o que no corresponde al sitio legítimo. Es crucial no hacer clic en enlaces sospechosos ni descargar archivos adjuntos de remitentes desconocidos o no verificados.\n    Los ciberdelincuentes que emplean el phishing apelan a emociones como el miedo, la curiosidad, la avaricia o el deseo de ayudar para manipular a sus víctimas. Si sospechas de un mensaje de phishing, no respondas ni interactúes con él. Contacta directamente a la entidad supuestamente remitente a través de sus canales oficiales (teléfono verificado o sitio web tecleado directamente en el navegador) para confirmar la autenticidad del mensaje. Si accidentalmente has revelado tus credenciales, cámbialas inmediatamente en todas las cuentas donde las utilices y monitoriza cualquier actividad sospechosa.',
    'Ingeniería Social',
    'Básico'
),
(
    'Creando Contraseñas Seguras y Únicas',
    'Las contraseñas son la llave de acceso a nuestra vida digital, por lo que su fortaleza es crucial. Una contraseña segura debe ser difícil de adivinar tanto para humanos como para programas automatizados (ataques de fuerza bruta o diccionario). Se recomienda una longitud mínima de 12 a 15 caracteres, e idealmente más. Debe incluir una combinación de letras mayúsculas, letras minúsculas, números y símbolos especiales (ej: !, @, #, $, %, ^, &, *, etc.).\n    Evita a toda costa usar información personal fácil de obtener (fechas de nacimiento, nombres de familiares o mascotas, aniversarios), palabras comunes del diccionario, nombres de equipos deportivos favoritos, o secuencias de teclado obvias (''123456'', ''password'', ''qwerty''). Un error crítico es reutilizar la misma contraseña en múltiples sitios web o servicios. Si una de esas cuentas se ve comprometida, todas las demás que usen la misma contraseña estarán en riesgo.\n    Dada la dificultad de crear y recordar docenas de contraseñas únicas y complexas, la solución más práctica y segura es el uso de un gestor de contraseñas. Estas aplicaciones generan contraseñas aleatorias y muy fuertes para cada servicio, las almacenan de forma cifrada y las autocompletan al iniciar sesión. El usuario solo necesita recordar una única contraseña maestra (que debe ser extremadamente fuerte) para acceder al gestor. Adicionalmente, muchos gestores de contraseñas ofrecen funcionalidades como la alerta por contraseñas comprometidas en brechas de datos conocidas o el almacenamiento seguro de notas.',
    'Gestión de Identidad',
    'Básico'
),
(
    'Tipos Comunes de Malware: Virus, Gusanos y Troyanos',
    'El ''malware'', abreviatura de ''software malicioso'', es un término genérico que describe cualquier programa o código diseñado con la intención de dañar, infiltrarse o realizar acciones no deseadas en un sistema informático sin el consentimiento del propietario. Comprender sus diferentes tipos es esencial para una mejor protección. Los virus informáticos son uno de los tipos más antiguos; se caracterizan por necesitar un programa o archivo anfitrión (como un ejecutable o un documento) para activarse y propagarse. Cuando el archivo infectado se ejecuta (por ejemplo, abrir un documento de Word con una macro maliciosa o ejecutar un programa descargado), el virus se activa, pudiendo replicarse a otros archivos, corromper datos, o realizar otras acciones dañinas.\n    A diferencia de los virus, los gusanos informáticos son piezas de malware auto-replicantes que no necesitan un archivo anfitrión y pueden propagarse de forma autónoma a través de redes, como internet o redes locales. Explotan vulnerabilidades en los sistemas operativos, aplicaciones de red o servicios para infectar nuevos sistemas sin requerir la intervención directa del usuario (más allá de la infección inicial, en algunos casos). Suelen causar daños al consumir un gran ancho de banda de red, sobrecargar servidores o instalar otro malware. Los troyanos, o caballos de Troya, se presentan como software legítimo, útil o entretenido para engañar a los usuarios y persuadirlos a que los instalen y ejecuten. Una vez activos, pueden realizar una variedad de acciones maliciosas, como proporcionar a los atacantes acceso remoto no autorizado al sistema (''puerta trasera''), robar credenciales, registrar las pulsaciones del teclado (keylogging), o descargar e instalar otras formas de malware, como spyware, adware o ransomware.\n    Otros tipos de malware incluyen el spyware (diseñado para espiar la actividad del usuario y recopilar información personal sin su conocimiento), el adware (que muestra publicidad no deseada y a menudo intrusiva), y las botnets (redes de ordenadores infectados, llamados ''zombies'', controlados remotamente por un atacante para realizar tareas coordinadas como ataques DDoS o envío masivo de spam). La protección contra el malware implica una combinación de software antivirus/antimalware actualizado, precaución al descargar archivos y hacer clic en enlaces, mantener el software del sistema y las aplicaciones parcheadas, y usar firewalls.',
    'Software Malicioso',
    'Intermedio'
),
(
    'Fortaleciendo tu Seguridad con la Autenticación de Dos Factores (2FA)',
    'La Autenticación de Dos Factores (2FA), también conocida como verificación en dos pasos o autenticación multifactor (MFA) si se usan más de dos factores, es una capa de seguridad adicional fundamental para proteger las cuentas en línea y los accesos a sistemas. Su principio básico es requerir al usuario que proporcione dos tipos diferentes de credenciales o ''factores'' para verificar su identidad, en lugar de depender únicamente de la contraseña (que es ''algo que el usuario sabe''). Estos factores suelen clasificarse en tres categorías: algo que sabes (como una contraseña o un PIN), algo que tienes (como un teléfono móvil que recibe códigos, una tarjeta inteligente o una llave de seguridad física USB), y algo que eres (un rasgo biométrico, como una huella dactilar, reconocimiento facial o de iris).\n    Cuando la 2FA está habilitada para un servicio, después de ingresar correctamente la contraseña, el sistema solicita el segundo factor. Los métodos más comunes para este segundo factor incluyen: códigos de un solo uso basados en tiempo (TOTP) generados por aplicaciones de autenticación como Google Authenticator, Microsoft Authenticator o Authy, que se instalan en el smartphone del usuario; códigos de un solo uso enviados por mensaje de texto SMS al teléfono registrado (aunque este método se considera menos seguro debido al riesgo de interceptación de SMS o duplicación de SIM); notificaciones push a una aplicación móvil que el usuario debe aprobar; o el uso de llaves de seguridad hardware (como las compatibles con FIDO2/WebAuthn, por ejemplo, YubiKey), que ofrecen un nivel de seguridad muy alto al requerir la presencia física del dispositivo.\n    La principal ventaja de la 2FA es que, incluso si un atacante logra obtener la contraseña de un usuario (a través de phishing, malware o una brecha de datos), no podrá acceder a la cuenta sin poseer también el segundo factor. Esto reduce drásticamente el riesgo de accesos no autorizados y el robo de identidad. Es crucial habilitar 2FA en todas las cuentas importantes que lo ofrezcan, como correos electrónicos, redes sociales, servicios bancarios y gestores de contraseñas.',
    'Gestión de Identidad',
    'Intermedio'
),
(
    'Introducción a las VPN: Privacidad y Seguridad en Línea',
    'Una Red Privada Virtual (VPN, por sus siglas en inglés de Virtual Private Network) es una tecnología de red que permite crear una conexión segura y cifrada a través de una red menos segura, como internet. Funciona estableciendo un ''túnel'' virtual entre el dispositivo del usuario (ordenador, smartphone, etc.) y un servidor remoto operado por el proveedor del servicio VPN. Todo el tráfico de internet que genera el usuario se enruta a través de este túnel cifrado. La encriptación es el proceso de codificar los datos para que solo puedan ser leídos por alguien que tenga la clave de descifrado correcta, lo que protege la información de ser interceptada y comprendida por terceros no autorizados, como hackers o administradores de red curiosos, especialmente cuando se utilizan redes Wi-Fi públicas.\n    Además de la seguridad que proporciona el cifrado, las VPN son una herramienta poderosa para mejorar la privacidad en línea. Al conectarse a través de un servidor VPN, la dirección IP real del usuario se oculta y se reemplaza por la dirección IP del servidor VPN. Esto hace mucho más difícil que los sitios web, los anunciantes o incluso el Proveedor de Servicios de Internet (ISP) rastreen la actividad en línea del usuario, su ubicación geográfica y sus hábitos de navegación. Las VPN también se utilizan para otros fines, como eludir la censura gubernamental o las restricciones geográficas impuestas por servicios de streaming para acceder a contenido que, de otro modo, no estaría disponible en la región del usuario. También pueden ayudar a evitar la limitación de velocidad (throttling) por parte del ISP, que a veces reduce la velocidad de ciertos tipos de tráfico. Es importante elegir un proveedor de VPN confiable, con una política clara de no registros (no-logs) y un cifrado robusto.',
    'Seguridad en Redes',
    'Intermedio'
),
(
    'La Importancia Vital de Mantener tu Software Actualizado',
    'El mantenimiento de software actualizado es una de las piedras angulares de una buena higiene digital y una defensa crítica contra las ciberamenazas. Esto aplica a todos los niveles de software: el sistema operativo (Windows, macOS, Linux, Android, iOS), los navegadores web, las aplicaciones de productividad (suites ofimáticas, editores de PDF), los programas de seguridad (antivirus, antimalware), las aplicaciones de comunicación, y hasta el firmware de dispositivos como routers o componentes de hardware. Las empresas y desarrolladores de software lanzan actualizaciones periódicamente no solo para introducir nuevas características o mejorar la usabilidad, sino, de manera fundamental, para corregir errores de programación y, especialmente, vulnerabilidades de seguridad que han sido descubiertas.\n    Una vulnerabilidad es una debilidad en el código o diseño de un software que puede ser explotada por un atacante para realizar acciones no autorizadas, como ejecutar código malicioso, acceder a información sensible, o tomar control del sistema afectado. Los ciberdelincuentes están constantemente buscando y desarrollando herramientas para explotar estas vulnerabilidades, especialmente aquellas que son conocidas y para las cuales ya existe un parche (actualización que corrige la falla). Ignorar o posponer las actualizaciones deja tus sistemas expuestos a estos ataques. Las vulnerabilidades de ''día cero'' (zero-day) son aquellas que son explotadas por atacantes antes de que el proveedor del software tenga conocimiento de ellas o haya podido lanzar un parche, pero incluso en estos casos, un sistema general bien actualizado puede presentar menos puntos de entrada o mitigar el impacto.\n    La mayoría de los sistemas operativos y muchas aplicaciones ofrecen la opción de actualizaciones automáticas. Es altamente recomendable habilitar esta función siempre que sea posible, ya que asegura que los parches de seguridad se apliquen tan pronto como estén disponibles, minimizando la ventana de oportunidad para los atacantes. Para software que no se actualiza automáticamente, es importante desarrollar el hábito de revisar e instalar actualizaciones manualmente de forma regular, obteniéndolas siempre de fuentes oficiales.',
    'Buenas Prácticas',
    'Básico'
),
(
    'Entendiendo el Papel de los Firewalls',
    'Un firewall o cortafuegos es un componente esencial de la seguridad informática que funciona como un filtro o barrera entre una red privada (como la de tu hogar u oficina, o incluso tu propio ordenador) e internet u otras redes. Su misión principal es monitorizar, filtrar y controlar el tráfico de red entrante y saliente basándose en un conjunto de reglas de seguridad predefinidas. Estas reglas determinan qué tipo de tráfico está permitido pasar y cuál debe ser bloqueado, protegiendo así la red interna de accesos no autorizados, intrusiones y ciertos tipos de ciberataques.\n    Existen diferentes tipos de firewalls. Los firewalls basados en host (o personales) son aplicaciones de software que se ejecutan en un ordenador individual y protegen únicamente a ese dispositivo. Suelen venir integrados en los sistemas operativos modernos. Los firewalls basados en red son típicamente dispositivos de hardware dedicados (aunque también pueden ser soluciones de software en servidores) que se colocan en el perímetro de una red (por ejemplo, entre la conexión a internet y el router de la red local) para proteger a todos los dispositivos conectados a esa red. Los firewalls más avanzados, conocidos como Next-Generation Firewalls (NGFW), incorporan funcionalidades adicionales como la inspección profunda de paquetes (DPI), sistemas de prevención de intrusiones (IPS), filtrado de aplicaciones y reconocimiento de malware.\n    Es importante entender que un firewall no es una solución de seguridad única y completa. Por ejemplo, no previene infecciones por virus a través de archivos adjuntos de correo electrónico si el correo ya ha sido permitido por las reglas del firewall (para eso se necesita un antivirus). Sin embargo, es una capa de defensa esencial que trabaja en conjunto con otras medidas de seguridad para crear una estrategia de ''defensa en profundidad'', ayudando a bloquear conexiones maliciosas, intentos de escaneo de puertos, y la propagación de ciertos tipos de malware que dependen de la red para comunicarse o expandirse.',
    'Seguridad en Redes',
    'Intermedio'
),
(
    'Ransomware: Secuestro de Datos y Cómo Protegerse',
    'El ransomware se ha consolidado como una de las amenazas cibernéticas más temidas y lucrativas para los delincuentes, afectando tanto a individuos como a organizaciones de todos los tamaños. Se trata de un tipo de software malicioso que, una vez que logra infiltrarse en un sistema o red, procede a cifrar (bloquear mediante criptografía) los archivos valiosos de la víctima –documentos, bases de datos, imágenes, vídeos, archivos de sistema– de manera que se vuelven completamente inaccesibles sin la clave de descifrado correcta. Tras el cifrado, los atacantes suelen mostrar un mensaje en la pantalla de la víctima o dejar un archivo de texto con instrucciones para el pago de un rescate, casi siempre exigido en criptomonedas como Bitcoin debido a su relativo anonimato y dificultad de rastreo, a cambio de la supuesta entrega de la clave de descifrado.\n    Las vías de infección del ransomware son variadas. Los más comunes incluyen correos electrónicos de phishing que contienen enlaces a sitios maliciosos o adjuntos infectados (como documentos de Office con macros maliciosas o archivos ZIP con ejecutables disfrazados), la explotación de vulnerabilidades en software desactualizado (sistemas operativos, navegadores, plugins, software de servidor), el uso de credenciales de acceso débiles o robadas (especialmente para servicios de acceso remoto como RDP), o incluso a través de descargas ''drive-by'' desde sitios web comprometidos. El impacto de un ataque de ransomware puede ser devastador, resultando en la pérdida permanente de datos, interrupción de operaciones comerciales, daño reputacional y costes financieros significativos, no solo por el posible pago del rescate (que no garantiza la recuperación) sino también por los costes de remediación y recuperación.\n    La prevención es la estrategia más efectiva. Esto incluye: realizar copias de seguridad frecuentes, completas y probadas, manteniendo al menos una copia offline o en un almacenamiento inmutable (aislada de la red para que no pueda ser cifrada); mantener todo el software y sistemas operativos rigurosamente actualizados con los últimos parches de seguridad; utilizar soluciones de seguridad endpoint robustas (antivirus/antimalware con protección específica contra ransomware); implementar una fuerte política de contraseñas y autenticación multifactor; educar a los usuarios para que reconozcan y eviten tácticas de phishing y descargas sospechosas; y segmentar las redes para limitar la propagación lateral en caso de una brecha. Contar con un plan de respuesta a incidentes que contemple específicamente el ransomware también es crucial.',
    'Software Malicioso',
    'Avanzado'
),
(
    'Navegación Segura: Consejos para Usar Wi-Fi Públicas',
    'Las redes Wi-Fi públicas que encontramos en aeropuertos, cafeterías, hoteles y otros lugares ofrecen una gran comodidad para mantenernos conectados fuera de casa o de la oficina. Sin embargo, esta conveniencia viene acompañada de riesgos de seguridad inherentes que los usuarios deben conocer y mitigar. Estas redes suelen ser menos seguras que las redes privadas, ya que a menudo carecen de cifrado robusto entre el dispositivo del usuario y el punto de acceso, o utilizan contraseñas compartidas y fáciles de obtener. Esto las convierte en un objetivo atractivo para ciberdelincuentes que buscan interceptar datos personales, credenciales de acceso o información financiera.\n    Uno de los riesgos más significativos en las Wi-Fi públicas es el ataque de ''Man-in-the-Middle'' (MitM), donde un atacante se interpone en la comunicación entre el usuario y el punto de acceso (o internet), pudiendo espiar, modificar o robar la información transmitida. Los atacantes también pueden configurar puntos de acceso falsos (''evil twins'') con nombres similares a los legítimos para engañar a los usuarios y hacer que se conecten a su red controlada. Para navegar de forma más segura en estas redes, es fundamental adoptar ciertas precauciones: evita realizar actividades sensibles como transacciones bancarias, compras en línea o iniciar sesión en cuentas importantes. Si es imprescindible, asegúrate de que la conexión al sitio web sea a través de HTTPS (busca el ícono del candado y ''https://'' en la barra de direcciones de tu navegador), lo que cifra la comunicación entre tu navegador y el servidor web.\n    Otras recomendaciones incluyen desactivar las funciones de compartir archivos y la detección de redes en tu dispositivo para hacerlo menos visible. ''Olvida'' la red Wi-Fi pública de la lista de redes guardadas después de usarla para evitar que tu dispositivo se reconecte automáticamente en el futuro. La medida de protección más completa y recomendada para usar Wi-Fi públicas es utilizar una Red Privada Virtual (VPN) de confianza. Una VPN cifra todo el tráfico de internet que sale de tu dispositivo, creando un túnel seguro hasta el servidor VPN, lo que hace que tus datos sean ilegibles para cualquiera que intente interceptarlos en la red local.',
    'Seguridad en Redes',
    'Básico'
),
(
    'Copias de Seguridad: Tu Red de Seguridad Digital',
    'Las copias de seguridad (backups) de datos son un componente absolutamente crítico de cualquier estrategia de protección de la información, tanto para usuarios individuales como para organizaciones. Su objetivo principal es crear duplicados de tus archivos y sistemas importantes para que puedan ser restaurados en caso de que los datos originales se pierdan, dañen o se vuelvan inaccesibles. Las causas de pérdida de datos son múltiples y variadas, incluyendo fallos de hardware (rotura de discos duros), errores humanos (borrado accidental de archivos), desastres naturales (incendios, inundaciones, terremotos), robos de dispositivos, o ciberataques, especialmente el ransomware, que cifra los datos y los hace inutilizables.\n    Una estrategia de copias de seguridad efectiva y resiliente suele seguir la conocida regla ''3-2-1''. Esta regla aconseja: tener al menos **tres** copias totales de tus datos importantes (la original y dos backups); almacenar estas copias en al menos **dos** tipos de medios de almacenamiento diferentes (por ejemplo, un disco duro interno, un disco duro externo USB, unidades NAS, cintas magnéticas, o almacenamiento en la nube); y mantener al menos **una** de esas copias en una ubicación geográficamente separada (off-site), es decir, fuera de tu casa u oficina principal. Esta copia off-site es crucial para la recuperación en caso de un desastre físico que afecte tu ubicación principal.\n    Existen diferentes tipos de backups, como los completos (copian todos los datos seleccionados cada vez), los incrementales (copian solo los datos que han cambiado desde el último backup, sea completo o incremental), y los diferenciales (copian los datos que han cambiado desde el último backup completo). Cada uno tiene sus pros y contras en términos de velocidad de backup/restauración y espacio de almacenamiento requerido. Independientemente del método, es fundamental no solo realizar las copias de seguridad de forma regular (diaria, semanal, según la criticidad de los datos), sino también probar periódicamente el proceso de restauración para asegurarse de que las copias son válidas y que sabes cómo recuperar la información cuando realmente la necesites.',
    'Buenas Prácticas',
    'Básico'
),
(
    'Comprendiendo los Ataques de Denegación de Servicio (DoS y DDoS)',
    'Los ataques de Denegación de Servicio (DoS) y Denegación de Servicio Distribuido (DDoS) son intentos maliciosos de interrumpir la disponibilidad de un servicio en línea, como un sitio web, una aplicación o una red completa, haciéndolo inaccesible para sus usuarios legítimos. Un ataque DoS se origina desde una única fuente (un solo ordenador o conexión a internet), mientras que un ataque DDoS es lanzado desde múltiples fuentes comprometidas y coordinadas, a menudo una ''botnet'' (una red de ordenadores infectados con malware y controlados por el atacante). La naturaleza distribuida de los ataques DDoS los hace mucho más difíciles de mitigar que los DoS.\n    El objetivo de estos ataques no suele ser robar información, sino sobrecargar los recursos del sistema objetivo hasta que no pueda responder a las solicitudes legítimas. Existen diversas técnicas para lograrlo, que se pueden clasificar en tres categorías principales: ataques volumétricos, que buscan saturar el ancho de banda de la red del objetivo con una gran cantidad de tráfico (ej: inundaciones UDP, inundaciones ICMP); ataques de protocolo, que explotan debilidades en los protocolos de red (ej: inundaciones SYN, que consumen recursos del servidor al dejar conexiones TCP semiabiertas); y ataques a la capa de aplicación, que se dirigen a vulnerabilidades específicas en las aplicaciones web para agotar los recursos del servidor (ej: inundaciones HTTP GET/POST).\n    El impacto de un ataque DoS/DDoS puede ser significativo, causando pérdidas financieras por la interrupción del servicio, daño a la reputación de la marca y frustración de los clientes. La mitigación de estos ataques es compleja y suele requerir una combinación de estrategias, como el uso de firewalls y sistemas de prevención de intrusiones (IPS), el aumento de la capacidad de ancho de banda, el uso de servicios especializados de mitigación de DDoS ofrecidos por proveedores de CDN (Content Delivery Network) o empresas de seguridad, el filtrado de tráfico malicioso, y la implementación de técnicas de ''rate limiting'' para controlar el número de solicitudes que un servidor acepta desde una misma fuente.',
    'Seguridad en Redes',
    'Intermedio'
),
(
    'Introducción a la Seguridad en la Nube: Modelos y Responsabilidades',
    'La computación en la nube (cloud computing) ha transformado la forma en que las empresas y los individuos almacenan datos y ejecutan aplicaciones, ofreciendo escalabilidad, flexibilidad y eficiencia. Sin embargo, también introduce nuevos desafíos y consideraciones de seguridad. La seguridad en la nube implica un conjunto de políticas, tecnologías y controles diseñados para proteger los datos, las aplicaciones y la infraestructura asociada a la nube contra amenazas internas y externas. Un concepto fundamental en la seguridad cloud es el ''modelo de responsabilidad compartida'', que define qué aspectos de la seguridad son responsabilidad del proveedor de la nube (como Amazon Web Services, Microsoft Azure, Google Cloud Platform) y cuáles son responsabilidad del cliente.\n    Este modelo varía según el tipo de servicio en la nube utilizado: Infraestructura como Servicio (IaaS), donde el cliente gestiona el sistema operativo, las aplicaciones y los datos, mientras el proveedor asegura la infraestructura física subyacente; Plataforma como Servicio (PaaS), donde el proveedor gestiona la infraestructura y el sistema operativo, y el cliente gestiona las aplicaciones y los datos; y Software como Servicio (SaaS), donde el proveedor gestiona casi todo y el cliente simplemente usa la aplicación y gestiona sus datos dentro de ella. En todos los modelos, el cliente siempre es responsable de la seguridad de sus propios datos, la gestión de identidades y accesos, y la configuración segura de los servicios que utiliza.\n    Las amenazas comunes en la nube incluyen accesos no autorizados debido a credenciales débiles o robadas, configuraciones incorrectas de los servicios cloud que exponen datos sensibles, interfaces de programación de aplicaciones (APIs) inseguras, secuestro de cuentas, y amenazas internas. Para mitigar estos riesgos, es crucial implementar medidas como una gestión de identidad y acceso robusta (incluyendo MFA), cifrado de datos en tránsito y en reposo, configuraciones seguras de los recursos en la nube, monitorización continua de la actividad, y el cumplimiento de las regulaciones y estándares de seguridad relevantes para la industria y la ubicación geográfica.',
    'Seguridad en la Nube',
    'Intermedio'
),
(
    'Más Allá del Phishing: Pretexting y Baiting en la Ingeniería Social',
    'La ingeniería social es el arte de manipular psicológicamente a las personas para que realicen acciones o divulguen información confidencial. Aunque el phishing es la técnica más conocida, existen otras variantes sofisticadas y efectivas. El ''pretexting'' es una de ellas, donde el atacante crea un escenario o pretexto elaborado (una historia inventada) para ganarse la confianza de la víctima y obtener información. A diferencia del phishing masivo, el pretexting suele ser más dirigido e interactivo. El atacante puede hacerse pasar por un compañero de trabajo, personal de soporte técnico, un investigador o cualquier otra figura de autoridad o confianza, utilizando información previamente investigada sobre la víctima o la organización para hacer su historia más creíble. El objetivo puede ser obtener datos personales, credenciales de acceso, o persuadir a la víctima para que realice una acción específica, como transferir dinero o instalar software.\n    Otra técnica de ingeniería social es el ''baiting'' (cebo). Como su nombre indica, el baiting consiste en ofrecer algo atractivo a la víctima para incitarla a realizar una acción que comprometa su seguridad. Este ''cebo'' puede ser físico, como dejar una unidad USB infectada con malware en un lugar público con una etiqueta llamativa (ej: ''''Salarios Empleados''''), esperando que la curiosidad lleve a alguien a conectarla a un ordenador de la red corporativa. También puede ser digital, como ofrecer descargas gratuitas de software, películas o música popular a través de sitios web o redes P2P, que en realidad contienen malware. El atacante confía en la curiosidad o la avaricia de la víctima.\n    La defensa contra estas técnicas de ingeniería social más elaboradas se basa en la concienciación y la desconfianza saludable. Es vital verificar siempre la identidad de cualquier persona que solicite información sensible o pida realizar acciones inusuales, utilizando canales de comunicación alternativos y conocidos. Se debe ser escéptico ante ofertas demasiado buenas para ser verdad y evitar conectar dispositivos USB de origen desconocido a los sistemas. Las organizaciones deben implementar políticas claras y realizar formaciones periódicas para ayudar a los empleados a reconocer y responder adecuadamente a estos intentos de manipulación.',
    'Ingeniería Social',
    'Intermedio'
),
(
    'Fundamentos de Criptografía: Protegiendo la Información Digital',
    'La criptografía es la ciencia y el arte de proteger la información mediante el uso de códigos y algoritmos matemáticos, de manera que solo las personas autorizadas puedan acceder a ella y comprenderla. Es un pilar fundamental de la ciberseguridad, ya que proporciona los mecanismos para asegurar la confidencialidad, integridad y autenticidad de los datos tanto cuando están almacenados (datos en reposo) como cuando se transmiten a través de redes (datos en tránsito). La confidencialidad asegura que la información solo sea accesible para quienes tienen permiso, la integridad garantiza que la información no ha sido alterada de forma no autorizada, y la autenticación verifica la identidad de las partes involucradas en una comunicación y el origen de los datos.\n    Existen dos tipos principales de algoritmos de cifrado. El cifrado simétrico (o de clave secreta) utiliza la misma clave tanto para cifrar el mensaje original (texto plano) como para descifrar el mensaje cifrado (texto cifrado). Ejemplos conocidos son AES (Advanced Encryption Standard) y DES (Data Encryption Standard). Es rápido y eficiente, pero el desafío radica en cómo compartir de forma segura la clave secreta entre el emisor y el receptor. El cifrado asimétrico (o de clave pública) utiliza un par de claves matemáticamente relacionadas: una clave pública, que se puede compartir abiertamente, y una clave privada, que debe mantenerse en secreto por su propietario. Lo que se cifra con una clave solo se puede descifrar con la otra. Un ejemplo prominente es RSA. Se utiliza para el intercambio seguro de claves simétricas, para las firmas digitales (donde se cifra un hash del mensaje con la clave privada del emisor, y cualquiera puede verificarlo con la clave pública del emisor, garantizando autenticidad y no repudio) y para el cifrado de mensajes.\n    Además del cifrado, las funciones hash criptográficas son cruciales. Un hash es un algoritmo que toma una entrada de cualquier tamaño y produce una cadena de caracteres de tamaño fijo (el ''''valor hash'''' o ''''digest''''). Es una función unidireccional (no se puede obtener la entrada original a partir del hash) y cualquier cambio mínimo en la entrada produce un hash completamente diferente. Se utilizan para verificar la integridad de los archivos (comparando hashes antes y después de la transmisión) y para almacenar contraseñas de forma segura (se almacena el hash de la contraseña, no la contraseña en sí). Comprender estos conceptos básicos de criptografía es esencial para apreciar cómo se protege nuestra información en el mundo digital.',
    'Criptografía',
    'Avanzado'
),
(
    'Gestión de Crisis Digital: Pasos Esenciales en la Respuesta a Incidentes',
    'Un incidente de seguridad es cualquier evento adverso que amenaza la confidencialidad, integridad o disponibilidad de los activos de información de una organización. Puede variar desde un ataque de malware o una brecha de datos hasta un acceso no autorizado o un fallo del sistema. La Respuesta a Incidentes (IR) es el proceso organizado y estructurado que sigue una entidad para prepararse, detectar, analizar, contener, erradicar y recuperarse de estos incidentes, minimizando su impacto y previniendo futuras ocurrencias. Contar con un Plan de Respuesta a Incidentes (IRP) bien definido y probado es crucial para una gestión eficaz de las crisis digitales.\n    El proceso de respuesta a incidentes se suele dividir en varias fases clave, a menudo referenciadas por acrónimos como PICERL (Preparación, Identificación, Contención, Erradicación, Recuperación y Lecciones Aprendidas). La fase de **Preparación** implica desarrollar el IRP, formar al equipo de respuesta (CSIRT - Computer Security Incident Response Team), adquirir las herramientas necesarias y realizar simulacros. La **Identificación** consiste en detectar que un incidente ha ocurrido (a través de alertas de sistemas de seguridad, informes de usuarios, etc.) y evaluar su alcance y severidad inicial.\n    Una vez identificado, la **Contención** busca limitar el daño y evitar que el incidente se propague más, por ejemplo, aislando los sistemas afectados de la red. La fase de **Eradicación** se centra en eliminar la causa raíz del incidente, como el malware o la vulnerabilidad explotada, y asegurarse de que el atacante ya no tiene acceso. La **Recuperación** implica restaurar los sistemas y datos afectados a su estado normal de operación a partir de copias de seguridad limpias y verificar que funcionan correctamente. Finalmente, la fase de **Lecciones Aprendidas** (o post-incidente) es fundamental: se analiza el incidente y la respuesta dada, se identifican las debilidades y se actualiza el IRP y las medidas de seguridad para mejorar la preparación ante futuros eventos. Una respuesta a incidentes rápida y eficiente puede marcar una gran diferencia en las consecuencias de un ciberataque.',
    'Gestión de Incidentes',
    'Avanzado'
); */